http:
  port: "8081"
  
sfdc1:
  username: ""
  password: ""
  token: ""

workdir:
   path : "......................./workdata"

postgresql:
  url: "jdbc:postgresql://localhost:5432/northwind"
  password: ""
  user: "postgres"
  driver_name: "org.postgresql.Driver"
  
db:
  ##host: "mudb.learn.mulesoft.com"
  ##port: "3306"
  ##user: "mule"
  ##password: "mule"
  ##database: "training"

aws:
  RegionEndpoint : "ap-northeast-1"
  Accesskey : ""
  Secretkey : ""
  buketname : ""
  
mysql_1:
 host: "localhost"
 password: ""
 user: "root"
 dbase: "Northwind"
 port: "3306"
 
mysql_2:
 host: "localhost"
 password: ""
 user: "root"
 dbase: "mulesoft"
 port: "3306"